### ISSUE TITLE
delete agents

### ISSUE THREAD

**Issue by antton** [BadChoice/handesk#75]
Hi, 

Is there any visual way via UI to delete agent users? Or I need to remove via database?

Thanks!

**Comment by BadChoice** [comment]
Hi,
Actually there is no visual way to delete them right now, so you should do it in the database, however, It would be good to add this feature so that when deleting an agent, all its tickets and leads are set to null `user_id`.

I believe I can work on this one soon, however a simple PR would be really appreciated as well

THanks!
