### ISSUE TITLE
Scrollbars appearing 

### ISSUE THREAD

**Issue by adriahn** [BadChoice/handesk#97]
Good afternoon,

after installing on a clean ubuntu server with php7+apache2 we encounter that the design is a bit akward showing the scrollbars everywhere.

I've tested in all browsers, same result. 

![handesk-github](https://user-images.githubusercontent.com/30721466/36170127-c0f79e5a-10fe-11e8-8cbe-927030ffb7c4.JPG)

Anyone can help? Many thanks

**Comment by adriahn** [comment]
So... I guess is bootstrap/css related, as in my ipad I don't see any scrollbar... right?

**Comment by BadChoice** [comment]
It is not using bootstrap, but yeah, looks like something CSS related

Jordi Puigdellívol

El 14 de febrero de 2018 a las 9:25:53, adriahn (notifications@github.com)
escribió:

So... I guess is bootstrap/css related, as in my ipad I don't see any
scrollbar... right?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/BadChoice/handesk/issues/97#issuecomment-365529996>,
or mute
the thread

**Comment by adriahn** [comment]
@BadChoice 
 massive thanks for replying so quickly!

I was doing some tests, and I've managed to hide it from chrome adding this to all.css

`.sidebar::-webkit-scrollbar{display:none}`

Reading the only way to hide it from all browsers is putting one container on top of the another with this settings, served as an example.

`#container1 {
    height: 100%;
    width: 100%;
    border: 1px solid green;
    overflow: hidden;
    position: relative;
}
#container2 {
    position: absolute;
    top: 0px;
    bottom: 0px;
    left: 0px;
    right: -15px;
    border: 1px solid blue;
    overflow: auto;
}`

**Comment by BadChoice** [comment]
Sounds good!
feel free to send me a PR so I can merge it to the master branch ;)


Encès 14 de febrer de 2018 a 10:17:26, adriahn (notifications@github.com)
va escriure:

@BadChoice <https://github.com/badchoice>
massive thanks for replying so quickly!

I was doing some tests, and I've managed to hide it from chrome adding this
to all.css

.sidebar::-webkit-scrollbar{display:none}

Reading the only way to hide it from all browsers is putting one container
on top of the another with this settings, served as an example.

#container1 { height: 100%; width: 100%; border: 1px solid green; overflow:
hidden; position: relative; } #container2 { position: absolute; top: 0px;
bottom: 0px; left: 0px; right: -15px; border: 1px solid blue; overflow:
auto; }

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/BadChoice/handesk/issues/97#issuecomment-365542548>,
or mute
the thread

**Comment by edwade3** [comment]
I've created a PR (#102) to remove the scrollbars by setting overflow to auto. This means the nav scrolls vertically as there's more content than space but you don't get the horizontal ones.
